# Generated by Django 2.0.6 on 2018-10-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('fields_name', models.CharField(max_length=200)),
                ('stars', models.IntegerField(default=0)),
                ('release_date', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
