# Generated by Django 2.0.6 on 2018-10-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='question',
        ),
        migrations.RemoveField(
            model_name='book',
            name='votes',
        ),
    ]
